### PR TITLE
fix: return to noIndex script

### PR DESCRIPTION
**Pull request by randychilau**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

I thought I had some idea of how to do this, but was unsuccessful with every try to get the site to use pathPrefix, and now the url only shows the README.

Hopefully you can get things back on track, and if you have the time, please explain my errors or wrong assumptions, I am happy to learn.

I thought I could merge a copy of the mdx2 branch into the master, and then it would build and deploy using the pathPrefix settings, and the url https://layer5labs.github.io/layer5/ would display the site.

I tried different command scripts but can't seem to get it to work, what am I missing?

Also ran into this error when I tried to add the "gh-pages -d public -b master" command to the noIndex script:

```
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'runner@fv-az354-505.(none)')

Error: Process completed with exit code 1.
```

Anyway, thanks for giving me a chance to try, and look forward to hearing the solution.

Cheers,
Randy

**Comment by Nikhil-Ladha** [comment]
The site is up and running again :), https://layer5labs.github.io/layer5
The thing is in this repo, and even in the original repo when we build the site using Gtihub action we build the site and push the changes to a branch named `site` from where the site is being hosted, this helps us save Netlify build minutes such that eveything is being taken care of by Github actions (hail open source) and nothing happens on Netlify apart from copying the `public` directory and hosting there.

So, in this repo I just changed the host branch back to `site` and things started working, check it out yourself on the setting page and also take a look at the `site` branch once, you will understand.

**Comment by Nikhil-Ladha** [comment]
Secondly, please don't remove the `noIndex` command while deploying demo sites else it will be scanned by google and indexed, which we _really don't want_ to happen.

**Comment by Nikhil-Ladha** [comment]
Also, if I am not wrong all your changes from the opne PR are merged in this repo and the latest build includes that, so I think everything seems to be working fine and as expected. Cheers 💯

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

🙏 Thanks for the explanation!  

I looked at `site` in the workflow yaml, but thought it was some variable that was self-populating or something. I focused way too much on the scripts instead of looking at the code and understanding what each part was doing and where it was doing it. Very humbling and good reminder about how to evaluate code and/or troubleshoot issues. 

Understood regarding the `noIndex` and its importance. I was doing trial and error and just trying different things. Unfortunately for others, probably creating a lot of Github fail notifications for inboxes.

One note is that some of the builds on this repo failed due to memory issues, but they failed at a much different place than the usual `Building HTML Renderer` stage. The failure was happening after the  `Merge worker state` stage which I hadn't seen before. Also, if I re-ran the failed job, it would usually go through successfully. I am not sure if it is random, or if it is because in this workflow it has turned garbage-collecting (GC) off?

image
([source](https://github.com/layer5labs/layer5/actions/runs/5616067685/job/15218544985))

So if the PR gets merged, I will check to see if later builds are consistently completing for other PRs, because I am again concerned that we are very close to the default memory settings limit, and as more pages, images, etc get added it will exceed the limit. Also, I am going to ask the folks who have done the image updates if there is a way to resize images in certain folders programmatically (e.g. for community members).

Okay, I am going to try a couple more things now that you got things working properly again.

Thanks as always and have a nice weekend.

Cheers,
Randy

**Comment by randychilau** [comment]
Hi @Nikhil-Ladha,

Just a quick wrap up of stuff I tried.
- I tried to build a branch in another subdirectory e.g. "/layer5/test-pr", thinking maybe it would build in a separate directory and maintain the original folders and files in "/layer5", but as you probably already knew, that didn't work.
- There was a persistent build fail issue that I believe started when [this commit](https://github.com/layer5io/layer5/commit/fe7f28584aace5d96f81316fb892cf71e26d336d) was merged. I am not sure why it was causing the issue, but it happened consistently on [this repo](https://github.com/layer5labs/layer5/actions/runs/5624856142/job/15246294549) and the main[ layer5 repo](https://github.com/layer5io/layer5/actions/runs/5625575572/job/15244632300) (but only for the lhci builds?).

  Since the component involved in that commit was <InlineQuote> and I noticed it was part of the MDX workarounds. So I committed a change that removed it from the workarounds, and the builds started working again. I don't necessarily know why right now.

- Lastly, I was wondering how different Netlify hosting is from GitHub Pages hosting from a preview/trailing slash standpoint in terms of how often it would be needed to use this repo. 

  I think it is a subtle difference, but when a code source viewer is used for both trailing slash and non-trailing slash urls, it shows for "http://example.com/page/":
  - Netlify default settings will automatically forward trailing slash urls to `page.html`,
  - GitHub Pages requires an `index.html` in the "page" folder to redirect to `page.html`
  - This is supported by this [chart](https://github.com/slorber/trailing-slash-guide#summary).
 
 <details>
 <summary>example screenshot</summary>

image

 </details>
  
  So maybe this repo is necessary for testing any changes that involve redirects, but for everything else the Netlify preview is fine?

As usual, this is way too long, but for the sake of documentation.

Also, yes, now that the LCHI build issue is resolved, I think this can be given a second try for merging when everyone is ready.

Cheers,
Randy

**Comment by Nikhil-Ladha** [comment]
Yeah, we can use this repo to test out such corner cases where we see conflicting outputs for Netlify and Github pages.
Thanks for going through everything, let's get the discussion back on the actual PR under the layer5io/layer5 repo.

**Pull request merged**
